### ISSUE TITLE
Check if still works

### ISSUE THREAD

**Issue by farminf** [fsalomon/nespresso-expert-ble#1]
Hi, I want to write a small nodejs app for my expert machine and I did it based on your code but unfortunately it's not working. I wonder if yours still working or maybe you have some suggestions or considerations.. Thanks

**Comment by farminf** [comment]
Ok... finally I found a way, It needs to write other packets too, anyway thanks for releasing your script on GitHub

**Comment by onutrij** [comment]
Hi farminf. I tried the same as you but still not working. What is necessary to do? Is it possible to share the code?

Thank You

**Comment by farminf** [comment]
@onutrij Hi! sorry since I've written it for my ex-company I can't share the code.
But I'd be happy if I can help you.  Which information you exactly need? I can give you some info

**Comment by onutrij** [comment]
Hi Farmin,

thank you very much for your answer. That ´s a pity.
I thought about possibility to add Expert in Homebridge and then allow it
in Homekit.
Do you think it´s possible?
I was interested in what was missing in fsalomon repository.

Thank you

have a nice day

ne 25. 11. 2018 v 15:14 odesílatel Farmin <notifications@github.com> napsal:

**Comment by farminf** [comment]
@onutrij  yes definitely it's possible. I don't know exactly the homebridge but as I looked up, it is a nodejs server so for sure you can do that.

I have written a small gist to help you ( or anyone wanted to hack the expert machine ) this way it can be more clear and also useful maybe for others.
https://gist.github.com/farminf/94f681eaca2760212f457ac59da99f23

Hope it can help you. if you have any doubt just comment on it.

**Comment by sensnowy** [comment]
hey guys. did you guys complete the code for the nespresso expert and homebridge?

**Comment by sensnowy** [comment]
> @onutrij yes definitely it's possible. I don't know exactly the homebridge but as I looked up, it is a nodejs server so for sure you can do that.
> 
> I have written a small gist to help you ( or anyone wanted to hack the expert machine ) this way it can be more clear and also useful maybe for others.
> https://gist.github.com/farminf/94f681eaca2760212f457ac59da99f23
> 
> Hope it can help you. if you have any doubt just comment on it.

have you guys found a code that works wtih the nespresso expert and homebridge? i would really love to add that to mine. but since i suck at coding would love to ask if i could get a code.

**Comment by onutrij** [comment]
Hi 
Unfortunately still on my list to do. I hope I will be able to make some progress in oncoming weeks 

Have a nice day

**Comment by sensnowy** [comment]
Thanks so much. I just noticed it’s feature last week after having it for three months. 
Sadly I am too noob to figure it out. 

> Am 10.04.2019 um 11:21 schrieb onutrij <notifications@github.com>:
> 
> Hi 
> Unfortunately still on my list to do. I hope I will be able to make some progress in oncoming weeks 
> 
> Have a nice day 
> 
> 
>

**Comment by AndrexOfficial** [comment]
Did anyone found a way to connect Nespresso machines to Homebridge? Thanks @onutrij @sensnowy @farminf

**Comment by sensnowy** [comment]
I don’t think anyone has been working on it anymore.

**Comment by farminf** [comment]
Sorry I can't help cause I don't have Homebridge...

**Comment by AndrexOfficial** [comment]
> Sorry I can't help cause I don't have Homebridge...

It is available for almost all platforms, MacOS and Windows 10 included
