### ISSUE TITLE
Not right value

### ISSUE THREAD

**Issue by tikismoke** [fsalomon/nespresso-expert-ble#2]
https://github.com/fsalomon/nespresso-expert-ble/blob/9e325f849078c6ea2dd2816b8c8462b8c19bd610/index.js#L52
Here hot water is 05 value but it's the same as americano.

From here :
https://gist.github.com/farminf/94f681eaca2760212f457ac59da99f23
it seems hot water is 04

**Comment by fsalomon** [comment]
Fixed. Thanks!
